global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'proxy-checker'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'proxy-checker'
    static_configs:
      - targets: ['proxy-checker:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

